"""
Federated AI Copilot reply service.
Enhanced with lightweight LLM (HuggingFace) + deterministic fallback.
"""
from typing import Any, Dict, List, Optional
import re
import logging
from sqlalchemy.orm import Session

from app.services.copilot_context_service import CopilotContextService
from app.services.federated_intelligence_service import FederatedIntelligenceService
from app.services.copilot_llm_service import CopilotLLMService

logger = logging.getLogger(__name__)


SYSTEM_PROMPT_TEMPLATE = (
    "You are a Federated Healthcare Intelligence Copilot. "
    "You must answer using only the structured platform context. "
    "You must respect role-based access. "
    "You must explain federated training impact, differential privacy effects, "
    "aggregation mechanisms, and governance traceability. "
    "Never fabricate datasets, rounds, hospitals, or metrics."
)


class CopilotService:
    @staticmethod
    def chat(
        db: Session,
        current_user: Dict[str, Any],
        message: str,
        mode: str,
        page_context: Dict[str, Any],
    ) -> Dict[str, Any]:
        role = current_user.get("role", "HOSPITAL")
        user_obj = current_user.get("db_object")
        hospital_id: Optional[int] = user_obj.id if role == "HOSPITAL" and user_obj else None

        context = CopilotContextService.build_context(
            db=db,
            role=role,
            hospital_id=hospital_id,
            page_context=page_context,
        )

        # ========== LLM ENHANCEMENT LAYER (with fallback) ==========
        # Use LLM only for analysis-heavy modes to keep common interactions responsive
        if CopilotService._should_use_llm(mode) and CopilotLLMService.is_enabled():
            try:
                logger.info(f"Attempting LLM response for query: {message[:100]}")
                llm_result = CopilotLLMService.generate_response(
                    message=message,
                    context=context,
                    role=role,
                )
                
                # If LLM succeeded (not fallback), return immediately
                if not llm_result.get("fallback_used"):
                    logger.info(f"LLM response successful with model: {llm_result.get('model_used')}")
                    
                    # Build recommendations and guardrails
                    recommendations = CopilotService._recommendations(context, role)
                    guardrails = [
                        "No raw patient-level data is returned.",
                        "Response is AI-generated using structured metadata only.",
                        "Role-based access constraints are enforced.",
                        f"Generated by: {llm_result.get('model_used')}",
                        f"Response time: {llm_result.get('response_time')}s",
                    ]
                    
                    # Add guardrail warnings if triggered
                    for trigger in llm_result.get("guardrails_triggered", []):
                        guardrails.append(f"Safety: {trigger}")
                    
                    return {
                        "answer": llm_result["answer"],
                        "mode": mode,
                        "role": role,
                        "context_used": context,
                        "links": [],  # LLM doesn't generate links (yet)
                        "recommendations": recommendations,
                        "guardrails": guardrails,
                    }
                else:
                    logger.warning(f"LLM returned fallback, using rule-based system: {llm_result.get('guardrails_triggered')}")
                    
            except Exception as e:
                logger.error(f"LLM layer exception: {str(e)}, falling back to rule-based")
        
        # ========== RULE-BASED FALLBACK (existing logic) ==========
        lowered = message.lower()
        links: List[Dict[str, str]] = []
        recommendations: List[str] = []

        # PAGE-AWARE GREETING: Detect if user is asking for help or just opened copilot
        if CopilotService._is_greeting_or_help_query(lowered, message):
            answer = CopilotService._get_page_aware_greeting(page_context, context, role)
            recommendations.extend(CopilotService._get_page_aware_suggestions(page_context, context, role))

        # HOSPITAL INTENT HANDLERS
        elif (hospital_answer := CopilotService._hospital_intent_answer(lowered, context, role)):
            answer = hospital_answer

        elif "why" in lowered and "prediction" in lowered and page_context.get("prediction_id"):
            analysis = FederatedIntelligenceService.explain_prediction(
                db=db,
                prediction_id=page_context["prediction_id"],
                role=role,
                hospital_id=hospital_id,
            )
            answer = CopilotService._format_prediction_answer(analysis)
            links.append({"label": "Prediction Details", "url": f"/prediction-detail/{page_context['prediction_id']}"})

        elif "round" in lowered and ("better" in lowered or "compare" in lowered):
            current_round = page_context.get("round_number") or CopilotService._extract_round_number(message)
            previous_round = (current_round - 1) if isinstance(current_round, int) and current_round > 1 else None
            if current_round and previous_round:
                comparison = FederatedIntelligenceService.compare_rounds(db, previous_round, current_round)
                answer = CopilotService._format_round_comparison_answer(comparison, previous_round, current_round)
                links.append({"label": f"Round {current_round}", "url": f"/aggregation/round/{current_round}"})
            else:
                answer = "I need a valid round context to compare rounds. Open a round detail page and ask again."

        elif "epsilon" in lowered or "privacy" in lowered or "dp" in lowered:
            governance = context.get("governance", {})
            answer = CopilotService._format_dp_answer(governance)
            links.append({"label": "Governance", "url": "/governance"})

        elif "weight" in lowered and ("rejected" in lowered or "failed" in lowered or "troubleshoot" in lowered):
            diagnosis = FederatedIntelligenceService.diagnose_submission_issue(
                db=db,
                round_number=page_context.get("round_number"),
                role=role,
                hospital_id=hospital_id,
            )
            answer = CopilotService._format_troubleshooting_answer(diagnosis)
            links.append({"label": "Training", "url": "/training"})

        elif "verify" in lowered and "integrity" in lowered:
            round_number = page_context.get("round_number")
            if round_number:
                audit = FederatedIntelligenceService.audit_round(db, round_number)
                answer = CopilotService._format_audit_answer(audit)
                links.append({"label": "Blockchain Audit", "url": "/blockchain-audit"})
            else:
                answer = "Open a specific round and ask again to verify round integrity."

        elif "executive summary" in lowered:
            answer = CopilotService._format_executive_summary(context)
            links.append({"label": "Aggregation", "url": "/aggregation" if role == "ADMIN" else "/dashboard"})

        elif "all predictions" in lowered and "round" in lowered:
            target_round = page_context.get("round_number") or CopilotService._extract_round_number(message)
            if target_round:
                listing = FederatedIntelligenceService.list_predictions_by_round(
                    db=db,
                    round_number=target_round,
                    role=role,
                    hospital_id=hospital_id,
                )
                answer = CopilotService._format_prediction_round_listing(listing)
            else:
                answer = "I need a round context to list predictions. Open a round page and ask again."
            links.append({"label": "Predictions", "url": "/predictions"})

        else:
            answer = CopilotService._format_general_answer(context, mode, message)

        # Add page-aware recommendations
        recommendations.extend(CopilotService._get_page_aware_recommendations(page_context, context, role))
        recommendations.extend(CopilotService._recommendations(context, role))

        guardrails = [
            "No raw patient-level data is returned.",
            "Response is grounded in structured platform metadata.",
            "Role-based access constraints are enforced.",
        ]

        return {
            "answer": answer,
            "mode": mode,
            "role": role,
            "context_used": context,
            "links": links,
            "recommendations": recommendations,
            "guardrails": guardrails,
        }

    @staticmethod
    def _format_prediction_answer(analysis: Dict[str, Any]) -> str:
        if analysis.get("error"):
            return analysis["error"]

        top_features = analysis.get("top_features", [])
        feature_text = ", ".join([f"{f['feature']} ({f['importance']:.3f})" for f in top_features[:3]]) if top_features else "no feature attribution available"
        ci = analysis.get("confidence_interval") or {}

        return (
            f"Clinical + technical explanation: this prediction is tied to model type {analysis.get('model_type')} "
            f"from round {analysis.get('round_number')}. "
            f"Top contributing features are {feature_text}. "
            f"Confidence interval metadata: lower={ci.get('lower')}, upper={ci.get('upper')}. "
            f"Federated impact: participants={analysis.get('federated_training_impact', {}).get('participants')}, "
            f"DP epsilon={analysis.get('federated_training_impact', {}).get('dp_epsilon')}."
        )

    @staticmethod
    def _format_round_comparison_answer(comparison: Dict[str, Any], r1: int, r2: int) -> str:
        if comparison.get("error"):
            return comparison["error"]

        return (
            f"Round {r2} vs Round {r1}: accuracy delta={comparison.get('accuracy_delta'):.4f}, "
            f"loss delta={comparison.get('loss_delta'):.4f}, participants delta={comparison.get('participants_delta')}, "
            f"DP epsilon delta={comparison.get('dp_epsilon_delta'):.4f}. "
            f"Likely drivers are participation mix, privacy noise level, and aggregation contribution spread."
        )

    @staticmethod
    def _format_dp_answer(governance: Dict[str, Any]) -> str:
        dp = (governance or {}).get("dp", {})
        epsilon = dp.get("epsilon")
        if epsilon is None:
            return "No DP budget metadata found in current context."

        return (
            f"DP epsilon is {epsilon}. Lower epsilon means stronger privacy and typically more utility tradeoff. "
            f"Current delta is {dp.get('delta')}, epsilon spent is {dp.get('epsilon_spent')}. "
            f"Use this to balance compliance risk vs model accuracy."
        )

    @staticmethod
    def _format_troubleshooting_answer(diagnosis: Dict[str, Any]) -> str:
        if diagnosis.get("summary"):
            return diagnosis["summary"]
        issues = diagnosis.get("issues", [])
        issue_text = "; ".join(issues) if issues else "No issue detected"
        return (
            f"Submission diagnosis for round {diagnosis.get('round_number')}: {issue_text}. "
            f"Model #{diagnosis.get('model_id')} uploaded={diagnosis.get('is_uploaded')}, "
            f"mask_uploaded={diagnosis.get('is_mask_uploaded')}."
        )

    @staticmethod
    def _format_audit_answer(audit: Dict[str, Any]) -> str:
        if audit.get("error"):
            return audit["error"]
        integ = audit.get("integrity", {})
        privacy = audit.get("privacy", {})
        return (
            f"Round {audit.get('round_number')} integrity status: immutable_recorded={integ.get('immutable_recorded')}, "
            f"block_hash={integ.get('block_hash')}, model_hash={integ.get('model_hash')}. "
            f"Privacy metadata: epsilon={privacy.get('epsilon')}, delta={privacy.get('delta')}."
        )

    @staticmethod
    def _format_executive_summary(context: Dict[str, Any]) -> str:
        rounds = context.get("recent", {}).get("latest_rounds", [])
        if not rounds:
            return "No round metadata available to produce an executive summary."

        top = rounds[0]
        return (
            f"Executive summary: latest round {top.get('round_number')} status={top.get('status')}, "
            f"participants={top.get('participants')}, accuracy={top.get('accuracy')}. "
            f"Governance snapshot includes DP/MPC/blockchain records in current context. "
            f"Recommendation: review participation variance and privacy budget trend before next round."
        )

    @staticmethod
    def _format_prediction_round_listing(listing: Dict[str, Any]) -> str:
        predictions = listing.get("items", [])
        if not predictions:
            return "No predictions found for the selected round in current role scope."

        lines = [
            f"Prediction #{p['id']} | round={listing.get('round_number')} | type={p.get('model_type')} | at={p.get('prediction_timestamp') or p.get('created_at')}"
            for p in predictions
        ]
        return "Predictions in scope:\n" + "\n".join(lines[:10])

    @staticmethod
    def _format_general_answer(context: Dict[str, Any], mode: str, message: str) -> str:
        page = context.get("page")
        role = context.get("role")
        governance = context.get("governance", {})
        latest_rounds = context.get("recent", {}).get("latest_rounds", [])
        hospital_metrics = (context.get("recent", {}).get("hospital_metrics", {}) or {})

        if role == "HOSPITAL":
            latest_round_number = hospital_metrics.get("latest_round_number")
            latest_round_status = hospital_metrics.get("latest_round_status")
            if latest_round_number is None:
                round_text = "no rounds available"
            else:
                round_text = f"latest round {latest_round_number} ({latest_round_status})"

            return (
                f"Hospital overview: local models {hospital_metrics.get('local_model_count', 0)}, "
                f"federated models {hospital_metrics.get('federated_model_count', 0)}, "
                f"datasets {hospital_metrics.get('dataset_count', 0)}, "
                f"predictions {hospital_metrics.get('prediction_count', 0)}, "
                f"{round_text}."
            )

        lead = f"Federated copilot ({mode}) response for role={role}, page={page}."

        if role == "HOSPITAL":
            lead += (
                f" Your hospital summary: local_models={hospital_metrics.get('local_model_count', 0)}, "
                f"federated_models={hospital_metrics.get('federated_model_count', 0)}, "
                f"datasets={hospital_metrics.get('dataset_count', 0)}, "
                f"predictions={hospital_metrics.get('prediction_count', 0)}, "
                f"latest_round={hospital_metrics.get('latest_round_number')}({hospital_metrics.get('latest_round_status')})."
            )
        elif latest_rounds:
            latest = latest_rounds[0]
            lead += (
                f" Latest round={latest.get('round_number')} status={latest.get('status')} "
                f"participants={latest.get('participants')} accuracy={latest.get('accuracy')}."
            )

        dp = governance.get("dp", {})
        if dp.get("epsilon") is not None:
            lead += f" Current DP epsilon={dp.get('epsilon')} (delta={dp.get('delta')})."

        lead += f" Question focus: {message[:220]}"
        return lead

    @staticmethod
    def _recommendations(context: Dict[str, Any], role: str) -> List[str]:
        recs: List[str] = []

        if role == "HOSPITAL":
            recs.append("Participate in consecutive rounds to improve calibration stability.")
            recs.append("Validate schema mapping before weight submission to avoid rejection.")
        else:
            recs.append("Track underperforming hospitals by local-vs-global metric gap.")
            recs.append("Review epsilon trends to keep privacy-utility balance within policy.")
            recs.append("Use governance audit trail before promoting new global model versions.")

        return recs

    @staticmethod
    def _extract_round_number(message: str) -> Optional[int]:
        match = re.search(r"round\s*(\d+)", message.lower())
        if not match:
            return None
        return int(match.group(1))

    @staticmethod
    def _is_local_model_count_query(lowered: str) -> bool:
        has_count = "how many" in lowered or "count" in lowered or "number of" in lowered
        local_model_terms = [
            "local model",
            "local models",
            "local ml model",
            "local ml models",
            "local ai model",
            "local ai models",
        ]
        return (
            has_count
            and any(term in lowered for term in local_model_terms)
        )

    @staticmethod
    def _is_dataset_count_query(lowered: str) -> bool:
        return (
            ("how many" in lowered or "count" in lowered or "number of" in lowered)
            and ("dataset" in lowered or "datasets" in lowered)
        )

    @staticmethod
    def _is_prediction_count_query(lowered: str) -> bool:
        return (
            ("how many" in lowered or "count" in lowered or "number of" in lowered)
            and ("prediction" in lowered or "predictions" in lowered)
        )

    @staticmethod
    def _is_federated_model_count_query(lowered: str) -> bool:
        has_count = "how many" in lowered or "count" in lowered or "number of" in lowered
        return (
            has_count
            and (
                "global model" in lowered
                or "global models" in lowered
                or "federated model" in lowered
                or "federated models" in lowered
                or "global ml model" in lowered
                or "global ml models" in lowered
                or "federated ml model" in lowered
                or "federated ml models" in lowered
                or "participation" in lowered
            )
        )

    @staticmethod
    def _is_total_model_count_query(lowered: str) -> bool:
        return (
            ("how many" in lowered or "count" in lowered or "number of" in lowered)
            and ("model" in lowered or "models" in lowered)
            and "local" not in lowered
            and "global" not in lowered
            and "federated" not in lowered
            and not CopilotService._is_model_family_count_query(lowered)
        )

    @staticmethod
    def _hospital_intent_answer(lowered: str, context: Dict[str, Any], role: str) -> Optional[str]:
        if role != "HOSPITAL":
            return None

        metrics = (context.get("recent", {}).get("hospital_metrics", {}) or {})
        prediction_context = context.get("prediction") or {}

        if CopilotService._is_dataset_name_query(lowered):
            dataset_names = metrics.get("dataset_names", []) or []
            if not dataset_names:
                return "No datasets are available in your hospital scope right now."
            return f"Your hospital datasets ({len(dataset_names)}): {CopilotService._join_list(dataset_names, 15)}."

        if CopilotService._is_dataset_upload_query(lowered):
            return (
                f"Your hospital has {metrics.get('dataset_uploaded_count', metrics.get('dataset_count', 0))} uploaded dataset(s)."
            )

        if CopilotService._is_dataset_training_query(lowered):
            return (
                f"Datasets trained locally/federated in your hospital scope: "
                f"trained={metrics.get('dataset_trained_count', 0)}, "
                f"participated_in_federated={metrics.get('dataset_federated_count', 0)}."
            )

        if CopilotService._is_model_family_count_query(lowered):
            family = CopilotService._extract_model_family(lowered)
            total_by_family = (metrics.get("model_type_counts_total") or {}).get(family, 0)
            local_by_family = (metrics.get("model_type_counts_local") or {}).get(family, 0)
            federated_by_family = (metrics.get("model_type_counts_federated") or {}).get(family, 0)
            return (
                f"{family.upper()} models in your hospital scope: total={total_by_family}, "
                f"local={local_by_family}, federated={federated_by_family}."
            )

        if CopilotService._is_local_model_count_query(lowered):
            return (
                f"You currently have {metrics.get('local_model_count', 0)} local model(s) "
                f"available in your hospital scope."
            )

        if CopilotService._is_local_model_name_query(lowered):
            names = metrics.get("local_model_names", []) or []
            if not names:
                return "No local model names are available yet in your hospital scope."
            return f"Local models ({len(names)}): {CopilotService._join_list(names, 15)}."

        if CopilotService._is_federated_model_count_query(lowered):
            return (
                f"You currently have {metrics.get('federated_model_count', 0)} federated/global model(s) "
                f"available in your hospital scope."
            )

        if CopilotService._is_federated_model_name_query(lowered):
            names = metrics.get("federated_model_names", []) or []
            if not names:
                return "No federated model names are available yet in your hospital scope."
            return f"Federated models ({len(names)}): {CopilotService._join_list(names, 15)}."

        if CopilotService._is_global_model_count_query(lowered):
            return f"Global models available to your hospital context: {metrics.get('global_model_count', 0)}."

        if CopilotService._is_global_model_name_query(lowered):
            names = metrics.get("global_model_names", []) or []
            if not names:
                return "No global model names are currently available."
            return f"Global models ({len(names)}): {CopilotService._join_list(names, 15)}."

        if CopilotService._is_total_model_count_query(lowered):
            return (
                f"You currently have {metrics.get('total_model_count', 0)} total model(s) in hospital scope: "
                f"local={metrics.get('local_model_count', 0)}, federated={metrics.get('federated_model_count', 0)}, "
                f"global={metrics.get('global_model_count', 0)}."
            )

        if CopilotService._is_dataset_count_query(lowered):
            return f"You currently have {metrics.get('dataset_count', 0)} dataset(s) in your hospital scope."

        if CopilotService._is_prediction_count_query(lowered):
            return f"You currently have {metrics.get('prediction_count', 0)} prediction record(s) in your hospital scope."

        if CopilotService._is_prediction_split_query(lowered):
            return (
                f"Prediction split in your hospital scope: local={metrics.get('prediction_local_count', 0)}, "
                f"global/federated={metrics.get('prediction_global_count', 0)}, "
                f"total={metrics.get('prediction_count', 0)}."
            )

        if "latest" in lowered and "prediction" in lowered:
            timestamp = metrics.get("latest_prediction_at")
            if timestamp:
                return f"Your latest hospital prediction was recorded at {timestamp}."
            return "No prediction records are available yet in your hospital scope."

        if CopilotService._is_prediction_insight_query(lowered):
            if not prediction_context:
                return (
                    "Open a specific prediction detail and ask again to get what it indicates, importance, "
                    "conclusion, and suggestion for that prediction."
                )

            # Extract prediction details
            prediction_id = prediction_context.get("id", "unknown")
            predicted_value = None
            dataset_name = prediction_context.get("dataset", "unknown dataset")
            model_type = prediction_context.get("model_type") or "unknown"
            round_number = prediction_context.get("round")
            accuracy = prediction_context.get("accuracy")
            training_type = prediction_context.get("training_type", "unknown")
            
            # Get feature importance
            top_features = prediction_context.get("feature_importance") or {}
            top_feature_text = "No feature-importance metadata available"
            if isinstance(top_features, dict) and top_features:
                ordered = sorted(top_features.items(), key=lambda item: item[1], reverse=True)[:3]
                top_feature_text = ", ".join([f"{feature} (importance: {importance:.3f})" for feature, importance in ordered])

            summary_text = prediction_context.get("summary_text") or "This is a forecast prediction generated by the federated learning model."
            confidence = prediction_context.get("confidence_interval")
            
            # Build comprehensive explanation
            explanation = f"📊 **Prediction #{prediction_id} Explanation:**\n\n"
            explanation += f"**What this predicts:** {summary_text}\n\n"
            explanation += f"**Model details:** {model_type} model (training type: {training_type})"
            if round_number is not None:
                explanation += f" from federated round {round_number}"
            explanation += ".\n\n"
            
            if accuracy:
                explanation += f"**Model accuracy:** {accuracy:.3f}\n\n"
            
            explanation += f"**Top contributing features:** {top_feature_text}\n\n"
            
            if confidence:
                explanation += f"**Confidence interval:** {confidence}\n\n"
            
            explanation += f"**Clinical interpretation:** This prediction was generated from {dataset_name} using a federated {model_type} model. "
            explanation += "The prediction incorporates patterns learned from multiple hospitals without sharing raw patient data. "
            
            explanation += f"\n\n**Recommendation:** Validate this forecast against current clinical observations and patient history. "
            if confidence:
                explanation += f"Monitor confidence interval {confidence} for uncertainty assessment. "
            explanation += "Consider this as decision support, not a replacement for clinical judgment."
            
            return explanation

        if CopilotService._is_active_round_query(lowered):
            latest_round_number = metrics.get("latest_round_number")
            latest_round_status = metrics.get("latest_round_status")
            has_active_round = bool(metrics.get("has_active_round"))
            if latest_round_number is None:
                return "No training rounds are available right now."
            if has_active_round:
                return (
                    f"Yes. Round {latest_round_number} is currently {latest_round_status}. "
                    f"This is the active federated round for your hospital context."
                )
            return (
                f"No active federated round right now. "
                f"Latest round is {latest_round_number} with status {latest_round_status}."
            )

        if CopilotService._is_target_column_query(lowered):
            latest_round_number = metrics.get("latest_round_number")
            target_column = metrics.get("latest_round_target_column")
            if latest_round_number is None:
                return "No training round data is available to identify a target column."
            if target_column:
                return f"The target column in the latest round ({latest_round_number}) is {target_column}."
            return f"Target column metadata is not available for the latest round ({latest_round_number})."

        if CopilotService._is_round_status_query(lowered):
            latest_round_number = metrics.get("latest_round_number")
            latest_round_status = metrics.get("latest_round_status")
            if latest_round_number is None:
                return "No training round is available right now."
            return f"Latest federated round is {latest_round_number} with status {latest_round_status}."

        if CopilotService._is_round_target_listing_query(lowered):
            rows = metrics.get("rounds_with_targets", []) or []
            if not rows:
                return "No round metadata is available for target-column listing."
            text = "; ".join([
                f"R{row.get('round_number')}: target={row.get('target_column')}, model={row.get('model_type')}, status={row.get('status')}"
                for row in rows[:10]
            ])
            return f"Recent rounds and target columns (hospital-visible): {text}."

        if CopilotService._is_model_type_query(lowered):
            latest_round_number = metrics.get("latest_round_number")
            model_type = metrics.get("latest_round_model_type")
            if latest_round_number is None:
                return "No round metadata is available to identify model type."
            if model_type:
                return f"The model type configured for latest round ({latest_round_number}) is {model_type}."
            return f"Model type metadata is not available for latest round ({latest_round_number})."

        if CopilotService._is_model_metrics_query(lowered):
            return (
                f"Model metrics (hospital scope): accuracy={metrics.get('ri_accuracy')}, "
                f"precision={metrics.get('ri_precision')}, recall={metrics.get('ri_recall')}, "
                f"f1={metrics.get('ri_f1')}, calibration={metrics.get('ri_calibration')}."
            )

        if CopilotService._is_results_intelligence_query(lowered):
            return (
                f"Results intelligence (hospital scope): predictions={metrics.get('ri_total_predictions', metrics.get('prediction_count', 0))}, "
                f"risk(high/medium/low)=({metrics.get('ri_high_risk_count')}/{metrics.get('ri_medium_risk_count')}/{metrics.get('ri_low_risk_count')}), "
                f"avg_confidence={metrics.get('ri_average_confidence')}, schema_status={metrics.get('ri_schema_status')}, "
                f"schema_quality={metrics.get('ri_schema_quality')}, rounds_participated={metrics.get('ri_rounds_participated', metrics.get('participated_round_count', 0))}, "
                f"submission_timeliness={metrics.get('ri_submission_timeliness')}."
            )

        if CopilotService._is_eligibility_query(lowered):
            latest_round_number = metrics.get("latest_round_number")
            if latest_round_number is None:
                return "No round is available to evaluate hospital eligibility."

            is_eligible = bool(metrics.get("is_eligible_for_latest_round"))
            reason = metrics.get("eligibility_reason") or "No eligibility reason provided."
            if is_eligible:
                return f"You are eligible for round {latest_round_number}. {reason}"
            return f"You are not eligible for round {latest_round_number}. {reason}"

        if ("how many" in lowered or "count" in lowered) and "round" in lowered:
            return (
                f"Your hospital has participated in {metrics.get('participated_round_count', 0)} round(s) "
                f"based on available prediction history."
            )

        if "summary" in lowered or "overview" in lowered or "hospital info" in lowered:
            return (
                f"Hospital summary: datasets={metrics.get('dataset_count', 0)}, "
                f"local_models={metrics.get('local_model_count', 0)}, "
                f"federated_models={metrics.get('federated_model_count', 0)}, "
                f"global_models={metrics.get('global_model_count', 0)}, "
                f"predictions={metrics.get('prediction_count', 0)}, "
                f"participated_rounds={metrics.get('participated_round_count', 0)}."
            )

        return None

    @staticmethod
    def _should_use_llm(mode: str) -> bool:
        heavy_modes = {"deep_analysis", "governance_check"}
        return mode in heavy_modes

    @staticmethod
    def _is_active_round_query(lowered: str) -> bool:
        return (
            ("active" in lowered or "open" in lowered or "running" in lowered)
            and "round" in lowered
        )

    @staticmethod
    def _is_eligibility_query(lowered: str) -> bool:
        return (
            "eligible" in lowered
            or "eligibility" in lowered
            or ("can" in lowered and "participate" in lowered)
        )

    @staticmethod
    def _is_target_column_query(lowered: str) -> bool:
        return (
            "target column" in lowered
            or (("target" in lowered or "column" in lowered) and "round" in lowered)
        )

    @staticmethod
    def _is_round_status_query(lowered: str) -> bool:
        return (
            ("status" in lowered and "round" in lowered)
            or ("is round" in lowered)
        )

    @staticmethod
    def _is_model_type_query(lowered: str) -> bool:
        return (
            ("model type" in lowered and "round" in lowered)
            or ("what model" in lowered and "round" in lowered)
        )

    @staticmethod
    def _join_list(items: List[str], limit: int = 12) -> str:
        if not items:
            return "none"
        sliced = items[:limit]
        tail = "" if len(items) <= limit else f" ... (+{len(items) - limit} more)"
        return ", ".join(sliced) + tail

    @staticmethod
    def _contains_any(lowered: str, terms: List[str]) -> bool:
        return any(term in lowered for term in terms)

    @staticmethod
    def _is_dataset_name_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["dataset", "datasets"])
            and CopilotService._contains_any(lowered, ["name", "names", "list", "show"])
        )

    @staticmethod
    def _is_dataset_upload_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["dataset", "datasets"])
            and CopilotService._contains_any(lowered, ["uploaded", "upload"])
        )

    @staticmethod
    def _is_dataset_training_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["dataset", "datasets"])
            and CopilotService._contains_any(lowered, ["trained", "training", "federated", "participated"])
        )

    @staticmethod
    def _is_local_model_name_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["local model", "local models", "local ml model", "local ml models"])
            and CopilotService._contains_any(lowered, ["name", "names", "list", "show"])
        )

    @staticmethod
    def _is_federated_model_name_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["federated model", "federated models", "federated ml model", "federated ml models"])
            and CopilotService._contains_any(lowered, ["name", "names", "list", "show"])
        )

    @staticmethod
    def _is_global_model_count_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["how many", "count", "number of"])
            and CopilotService._contains_any(lowered, ["global model", "global models"])
        )

    @staticmethod
    def _is_global_model_name_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["global model", "global models"])
            and CopilotService._contains_any(lowered, ["name", "names", "list", "show"])
        )

    @staticmethod
    def _is_prediction_split_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["prediction", "predictions"])
            and CopilotService._contains_any(lowered, ["local and global", "local vs global", "split", "breakdown", "local", "global", "federated"])
            and CopilotService._contains_any(lowered, ["count", "how many", "number of"])
        )

    @staticmethod
    def _is_round_target_listing_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["round", "rounds"])
            and CopilotService._contains_any(lowered, ["target column", "target columns", "target"])
            and CopilotService._contains_any(lowered, ["list", "show", "all", "which", "what"])
        )

    @staticmethod
    def _is_model_metrics_query(lowered: str) -> bool:
        return (
            CopilotService._contains_any(lowered, ["model", "models", "performance", "metrics"])
            and CopilotService._contains_any(lowered, ["accuracy", "precision", "recall", "f1", "calibration", "metric", "metrics"])
        )

    @staticmethod
    def _is_prediction_insight_query(lowered: str) -> bool:
        # Match explicit insight questions
        if (CopilotService._contains_any(lowered, ["prediction", "this prediction"])
            and CopilotService._contains_any(lowered, ["indicates", "importance", "conclusion", "suggestion", "what does", "explain"])):
            return True
        
        # Match questions about predicted value
        if CopilotService._contains_any(lowered, ["predicted value", "prediction value", "this value", "this predicted"]):
            return True
        
        # Match "what is" + prediction-related terms
        if "what is" in lowered and CopilotService._contains_any(lowered, ["prediction", "predicted", "value", "result"]):
            return True
        
        # Match "explain" + any prediction term
        if "explain" in lowered and CopilotService._contains_any(lowered, ["prediction", "predicted", "value", "result", "this"]):
            return True
        
        # Match "what does" + "mean" or similar
        if CopilotService._contains_any(lowered, ["what does", "what's", "whats"]) and CopilotService._contains_any(lowered, ["mean", "indicate", "suggest"]):
            return True
        
        return False

    @staticmethod
    def _is_results_intelligence_query(lowered: str) -> bool:
        return CopilotService._contains_any(lowered, [
            "result intelligence",
            "results intelligence",
            "intelligence metrics",
            "risk distribution",
            "schema status",
            "submission timeliness",
            "confidence score",
        ])

    @staticmethod
    def _extract_model_family(lowered: str) -> str:
        if "tft" in lowered:
            return "tft"
        if "lasso" in lowered:
            return "multi_model_lasso"
        if "regression" in lowered:
            return "ml_regression"
        if "xgboost" in lowered:
            return "xgboost"
        if "lstm" in lowered:
            return "lstm"
        return "unknown"

    @staticmethod
    def _is_model_family_count_query(lowered: str) -> bool:
        has_count = CopilotService._contains_any(lowered, ["how many", "count", "number of"])
        has_model = CopilotService._contains_any(lowered, ["model", "models"])
        has_family = CopilotService._contains_any(lowered, ["tft", "lasso", "regression", "xgboost", "lstm"])
        return has_count and has_model and has_family

    @staticmethod
    def _is_greeting_or_help_query(lowered: str, message: str) -> bool:
        """Detect if user is greeting, asking for help, or just opened copilot."""
        # Empty or very short messages
        if len(message.strip()) == 0 or len(message.strip()) < 3:
            return True
        
        greeting_terms = ["hi", "hello", "hey", "help", "what can you do", "how can you help", 
                         "what can i ask", "guide me", "start", "intro", "greet"]
        return any(term in lowered for term in greeting_terms) and len(message.split()) <= 5

    @staticmethod
    def _get_page_aware_greeting(page_context: Dict[str, Any], context: Dict[str, Any], role: str) -> str:
        """Generate contextual greeting based on current page."""
        page = page_context.get("page", "dashboard")
        metrics = (context.get("recent", {}).get("hospital_metrics", {}) or {})
        
        greeting = "👋 Hi! I'm your Federated AI Copilot. "
        
        if page == "prediction_detail":
            prediction_id = page_context.get("prediction_id")
            prediction_ctx = context.get("prediction") or {}
            model_type = prediction_ctx.get("model_type", "unknown")
            greeting += f"You're viewing Prediction #{prediction_id} ({model_type} model). "
            greeting += "I can explain this prediction, show feature importance, confidence intervals, or suggest next actions. "
            greeting += "Try asking: 'What does this prediction indicate?' or 'What are the top features?'"
        
        elif page == "round_detail":
            round_num = page_context.get("round_number")
            round_ctx = context.get("round") or {}
            status = round_ctx.get("status", "unknown")
            greeting += f"You're viewing Round #{round_num} (status: {status}). "
            greeting += "I can show participants, compare with previous rounds, explain aggregation results, or verify integrity. "
            greeting += "Try asking: 'How many hospitals participated?' or 'Compare with previous round'"
        
        elif page == "dataset_detail":
            dataset_id = page_context.get("dataset_id")
            greeting += f"You're viewing Dataset #{dataset_id}. "
            greeting += "I can check training history, show schema status, or recommend next training steps. "
            greeting += "Try asking: 'Has this dataset been used in federated training?' or 'Show training history'"
        
        elif page == "datasets" or page == "/datasets":
            dataset_count = metrics.get("dataset_count", 0)
            greeting += f"You're on the Datasets page (you have {dataset_count} dataset(s)). "
            greeting += "I can list your datasets, show upload status, or guide you on preparing data. "
            greeting += "Try asking: 'What are my dataset names?' or 'How many datasets have been trained?'"
        
        elif page == "training" or page == "/training":
            local_models = metrics.get("local_model_count", 0)
            greeting += f"You're on the Training page (you have {local_models} local model(s)). "
            greeting += "I can show your local models, explain training parameters, or troubleshoot failed trainings. "
            greeting += "Try asking: 'How many local models do I have?' or 'Show my local model names'"
        
        elif page == "global-model" or page == "/global-model":
            global_models = metrics.get("global_model_count", 0)
            greeting += f"You're on the Global Model page (you have {global_models} global model(s)). "
            greeting += "I can show available global models, explain aggregation results, or compare model versions. "
            greeting += "Try asking: 'How many TFT models?' or 'Show global model names'"
        
        elif page == "predictions" or page == "/predictions":
            prediction_count = metrics.get("prediction_count", 0)
            greeting += f"You're on the Predictions page (you have {prediction_count} prediction(s)). "
            greeting += "I can show prediction split (local vs global), list predictions by round, or explain risk distribution. "
            greeting += "Try asking: 'How many predictions from local vs global models?' or 'Latest prediction timestamp'"
        
        elif page == "results-intel" or page == "/results-intel":
            greeting += "You're on the Results Intelligence page. "
            greeting += "I can show risk distribution, schema quality, confidence metrics, or participation analytics. "
            greeting += "Try asking: 'What are my results intelligence metrics?' or 'Show risk distribution'"
        
        elif page == "governance" or page == "/governance":
            greeting += "You're on the Governance page. "
            greeting += "I can explain DP budget, verify blockchain integrity, or show compliance status. "
            greeting += "Try asking: 'What is my current epsilon?' or 'Verify round integrity'"
        
        elif page == "blockchain-audit" or page == "/blockchain-audit":
            greeting += "You're on the Blockchain Audit page. "
            greeting += "I can verify audit trails, check immutability, or explain blockchain records. "
            greeting += "Try asking: 'Verify round integrity' or 'Show blockchain status'"
        
        else:  # dashboard or unknown page
            if role == "HOSPITAL":
                greeting += f"You're on the Dashboard. Your hospital has {metrics.get('dataset_count', 0)} dataset(s), "
                greeting += f"{metrics.get('local_model_count', 0)} local model(s), {metrics.get('prediction_count', 0)} prediction(s), "
                latest_round = metrics.get('latest_round_number')
                if latest_round:
                    greeting += f"and participated in round {latest_round}. "
                greeting += "I can answer questions about your data, models, predictions, rounds, and compliance. "
                greeting += "Try asking: 'Hospital summary' or 'Is there an active round?'"
            else:
                greeting += "I can help with federated intelligence, governance, and system-wide analytics."
        
        return greeting

    @staticmethod
    def _get_page_aware_suggestions(page_context: Dict[str, Any], context: Dict[str, Any], role: str) -> List[str]:
        """Generate contextual quick-prompt suggestions based on current page."""
        page = page_context.get("page", "dashboard")
        suggestions = []
        
        if page == "prediction_detail":
            suggestions.extend([
                "💡 Ask: 'What does this prediction indicate?'",
                "💡 Ask: 'What are the top features driving this?'",
                "💡 Ask: 'What is the confidence interval?'",
            ])
        
        elif page == "round_detail":
            suggestions.extend([
                "💡 Ask: 'How many hospitals participated?'",
                "💡 Ask: 'Compare with previous round'",
                "💡 Ask: 'What is the target column?'",
            ])
        
        elif page == "datasets" or page == "/datasets":
            suggestions.extend([
                "💡 Ask: 'What are my dataset names?'",
                "💡 Ask: 'How many datasets have been trained?'",
                "💡 Ask: 'How many uploaded datasets?'",
            ])
        
        elif page == "training" or page == "/training":
            suggestions.extend([
                "💡 Ask: 'How many local models?'",
                "💡 Ask: 'Show my local model names'",
                "💡 Ask: 'Troubleshoot training issues'",
            ])
        
        elif page == "global-model" or page == "/global-model":
            suggestions.extend([
                "💡 Ask: 'How many TFT models?'",
                "💡 Ask: 'Show global model names'",
                "💡 Ask: 'How many models total?'",
            ])
        
        elif page == "predictions" or page == "/predictions":
            suggestions.extend([
                "💡 Ask: 'How many predictions (local vs global)?'",
                "💡 Ask: 'Latest prediction timestamp'",
                "💡 Ask: 'Show predictions by round'",
            ])
        
        elif page == "results-intel" or page == "/results-intel":
            suggestions.extend([
                "💡 Ask: 'What are my results intelligence metrics?'",
                "💡 Ask: 'Show risk distribution'",
                "💡 Ask: 'Schema quality status'",
            ])
        
        elif page == "governance" or page == "/governance":
            suggestions.extend([
                "💡 Ask: 'What is my current epsilon?'",
                "💡 Ask: 'Show DP budget status'",
                "💡 Ask: 'Verify round integrity'",
            ])
        
        else:  # dashboard
            if role == "HOSPITAL":
                suggestions.extend([
                    "💡 Ask: 'Hospital summary'",
                    "💡 Ask: 'Is there an active round?'",
                    "💡 Ask: 'How many predictions?'",
                ])
        
        return suggestions

    @staticmethod
    def _get_page_aware_recommendations(page_context: Dict[str, Any], context: Dict[str, Any], role: str) -> List[str]:
        """Generate page-specific actionable recommendations."""
        page = page_context.get("page", "dashboard")
        recommendations = []
        metrics = (context.get("recent", {}).get("hospital_metrics", {}) or {})
        
        if page == "prediction_detail":
            recommendations.append("Review feature importance to validate prediction drivers align with clinical expectations.")
            recommendations.append("Check confidence interval width - wider intervals suggest higher uncertainty.")
        
        elif page == "round_detail":
            recommendations.append("Compare participation count with previous rounds to identify trends.")
            recommendations.append("Verify blockchain audit trail before accepting aggregation results.")
        
        elif page == "datasets" or page == "/datasets":
            dataset_count = metrics.get("dataset_count", 0)
            if dataset_count == 0:
                recommendations.append("Upload your first dataset to start participating in federated training.")
            else:
                recommendations.append("Ensure schema consistency across datasets before training.")
        
        elif page == "training" or page == "/training":
            is_eligible = metrics.get("is_eligible_for_latest_round")
            if is_eligible:
                recommendations.append("You're eligible for the active round - consider starting local training.")
            else:
                recommendations.append("Check eligibility requirements to participate in the next round.")
        
        elif page == "global-model" or page == "/global-model":
            recommendations.append("Download latest global model to improve prediction accuracy.")
            recommendations.append("Compare global model performance with your local baselines.")
        
        elif page == "predictions" or page == "/predictions":
            prediction_count = metrics.get("prediction_count", 0)
            if prediction_count < 5:
                recommendations.append("Generate more predictions to build confidence in model performance.")
        
        elif page == "results-intel" or page == "/results-intel":
            recommendations.append("Monitor risk distribution to identify potential prediction quality issues.")
            recommendations.append("Track submission timeliness to maintain good standing in federated rounds.")
        
        return recommendations
