"""baseline_phase_a_pro_schema

Revision ID: 092ec1d2afe3
Revises: 
Create Date: 2026-02-26 17:18:57.304805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092ec1d2afe3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('blockchain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('model_hash', sa.String(length=256), nullable=False),
    sa.Column('block_hash', sa.String(length=256), nullable=False),
    sa.Column('prev_block_hash', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_block_hash'), 'blockchain', ['block_hash'], unique=True)
    op.create_index(op.f('ix_blockchain_id'), 'blockchain', ['id'], unique=False)
    op.create_index(op.f('ix_blockchain_model_hash'), 'blockchain', ['model_hash'], unique=False)
    op.create_index(op.f('ix_blockchain_round_id'), 'blockchain', ['round_id'], unique=False)
    op.create_table('model_governance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('model_hash', sa.String(length=256), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('policy_details', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_governance_id'), 'model_governance', ['id'], unique=False)
    op.create_index(op.f('ix_model_governance_model_hash'), 'model_governance', ['model_hash'], unique=False)
    op.create_index(op.f('ix_model_governance_round_number'), 'model_governance', ['round_number'], unique=False)
    op.create_table('model_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('model_path', sa.String(length=512), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('training_type', sa.String(length=20), nullable=True),
    sa.Column('model_architecture', sa.String(length=20), nullable=True),
    sa.Column('local_loss', sa.Float(), nullable=True),
    sa.Column('local_accuracy', sa.Float(), nullable=True),
    sa.Column('local_mape', sa.Float(), nullable=True),
    sa.Column('local_rmse', sa.Float(), nullable=True),
    sa.Column('local_r2', sa.Float(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('is_mask_uploaded', sa.Boolean(), nullable=True),
    sa.Column('model_hash', sa.String(length=128), nullable=True),
    sa.Column('hash_algorithm', sa.String(length=50), nullable=True),
    sa.Column('weights_hash', sa.String(length=128), nullable=True),
    sa.Column('training_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['training_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'dataset_id', 'round_id', name='uq_hospital_dataset_round')
    )
    op.create_index('idx_round_global', 'model_weights', ['round_number', 'is_global'], unique=False)
    op.create_index(op.f('ix_model_weights_id'), 'model_weights', ['id'], unique=False)
    op.create_table('schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('schema_content', sa.Text(), nullable=False),
    sa.Column('category_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_versions_id'), 'schema_versions', ['id'], unique=False)
    op.create_index(op.f('ix_schema_versions_version'), 'schema_versions', ['version'], unique=True)
    op.create_table('training_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('global_model_id', sa.Integer(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('num_participating_hospitals', sa.Integer(), nullable=True),
    sa.Column('average_loss', sa.Float(), nullable=True),
    sa.Column('average_mape', sa.Float(), nullable=True),
    sa.Column('average_rmse', sa.Float(), nullable=True),
    sa.Column('average_r2', sa.Float(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRAINING', 'AGGREGATING', 'CLOSED', name='roundstatus'), nullable=True),
    sa.Column('training_enabled', sa.Boolean(), nullable=False),
    sa.Column('participation_policy', sa.String(length=20), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['global_model_id'], ['model_weights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_rounds_id'), 'training_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_training_rounds_round_number'), 'training_rounds', ['round_number'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('CAPACITY_WARNING', 'CAPACITY_CRITICAL', 'ANOMALY_DETECTION', 'FORECAST_DEGRADATION', 'DATA_QUALITY', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.Column('num_columns', sa.Integer(), nullable=True),
    sa.Column('column_names', sa.Text(), nullable=True),
    sa.Column('is_normalized', sa.Boolean(), nullable=True),
    sa.Column('normalized_path', sa.String(length=512), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('hospitals_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('bed_capacity', sa.Integer(), nullable=True),
    sa.Column('icu_capacity', sa.Integer(), nullable=True),
    sa.Column('specializations', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('accreditation_status', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('ownership_type', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('last_audit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospitals_profile_id'), 'hospitals_profile', ['id'], unique=False)
    op.create_table('model_masks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('mask_checksum', sa.String(length=128), nullable=False),
    sa.Column('mask_algorithm', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_weights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', name='uq_model_mask')
    )
    op.create_index(op.f('ix_model_masks_id'), 'model_masks', ['id'], unique=False)
    op.create_index(op.f('ix_model_masks_round_number'), 'model_masks', ['round_number'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_capacity_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_forecast_degradation', sa.Boolean(), nullable=True),
    sa.Column('email_model_updates', sa.Boolean(), nullable=True),
    sa.Column('email_data_quality', sa.Boolean(), nullable=True),
    sa.Column('inapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('inapp_capacity_alerts', sa.Boolean(), nullable=True),
    sa.Column('inapp_forecast_degradation', sa.Boolean(), nullable=True),
    sa.Column('inapp_model_updates', sa.Boolean(), nullable=True),
    sa.Column('inapp_data_quality', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationtype'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('privacy_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('epsilon_spent', sa.Float(), nullable=True),
    sa.Column('total_epsilon_budget', sa.Float(), nullable=True),
    sa.Column('mechanism', sa.String(length=100), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('noise_multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_budgets_id'), 'privacy_budgets', ['id'], unique=False)
    op.create_table('round_allowed_hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['training_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hospital_id', name='unique_round_hospital')
    )
    op.create_index(op.f('ix_round_allowed_hospitals_hospital_id'), 'round_allowed_hospitals', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_round_allowed_hospitals_id'), 'round_allowed_hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_round_allowed_hospitals_round_id'), 'round_allowed_hospitals', ['round_id'], unique=False)
    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('forecast_data', sa.JSON(), nullable=False),
    sa.Column('schema_validation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_weights.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['training_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_records_id'), 'prediction_records', ['id'], unique=False)
    op.create_table('schema_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('original_column', sa.String(length=255), nullable=False),
    sa.Column('canonical_field', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'original_column', name='unique_dataset_column_mapping')
    )
    op.create_index(op.f('ix_schema_mappings_id'), 'schema_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_mappings_id'), table_name='schema_mappings')
    op.drop_table('schema_mappings')
    op.drop_index(op.f('ix_prediction_records_id'), table_name='prediction_records')
    op.drop_table('prediction_records')
    op.drop_index(op.f('ix_round_allowed_hospitals_round_id'), table_name='round_allowed_hospitals')
    op.drop_index(op.f('ix_round_allowed_hospitals_id'), table_name='round_allowed_hospitals')
    op.drop_index(op.f('ix_round_allowed_hospitals_hospital_id'), table_name='round_allowed_hospitals')
    op.drop_table('round_allowed_hospitals')
    op.drop_index(op.f('ix_privacy_budgets_id'), table_name='privacy_budgets')
    op.drop_table('privacy_budgets')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_model_masks_round_number'), table_name='model_masks')
    op.drop_index(op.f('ix_model_masks_id'), table_name='model_masks')
    op.drop_table('model_masks')
    op.drop_index(op.f('ix_hospitals_profile_id'), table_name='hospitals_profile')
    op.drop_table('hospitals_profile')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_training_rounds_round_number'), table_name='training_rounds')
    op.drop_index(op.f('ix_training_rounds_id'), table_name='training_rounds')
    op.drop_table('training_rounds')
    op.drop_index(op.f('ix_schema_versions_version'), table_name='schema_versions')
    op.drop_index(op.f('ix_schema_versions_id'), table_name='schema_versions')
    op.drop_table('schema_versions')
    op.drop_index(op.f('ix_model_weights_id'), table_name='model_weights')
    op.drop_index('idx_round_global', table_name='model_weights')
    op.drop_table('model_weights')
    op.drop_index(op.f('ix_model_governance_round_number'), table_name='model_governance')
    op.drop_index(op.f('ix_model_governance_model_hash'), table_name='model_governance')
    op.drop_index(op.f('ix_model_governance_id'), table_name='model_governance')
    op.drop_table('model_governance')
    op.drop_index(op.f('ix_blockchain_round_id'), table_name='blockchain')
    op.drop_index(op.f('ix_blockchain_model_hash'), table_name='blockchain')
    op.drop_index(op.f('ix_blockchain_id'), table_name='blockchain')
    op.drop_index(op.f('ix_blockchain_block_hash'), table_name='blockchain')
    op.drop_table('blockchain')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
